# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29f3ddd0c397686cb43581fe3631226f2d218884fcf942fb6616d82e9a6a30ec15788e19e742507d1cd5748adafb97259f7e0ef7781582e216812ec3324a71be

test:
  secret_key_base: a37cb379c6aa423ec59d0eabdf98c882ef70cb4a6c44f805f8bd210625ee59391ff4ec2624441290567adf5bafad20c939d55d57e6e3b532f84a2c31f22df2e1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
